[build-system]
build-backend = "setuptools.build_meta"
## #############################################################################
# Project
## #############################################################################
requires = [ "setuptools>=45", "setuptools-scm[toml]>=6.2", "wheel" ]

[project]
name = "spgrep-modulation"
description = "Collective atomic modulation analysis with irreducible space-group representation"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Kohei Shinohara", email = "kshinohara0508@gmail.com" },
]
requires-python = ">=3.10"
classifiers = [
  # Full list: https://pypi.python.org/pypi?%3Aaction=list_classifiers
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Physics",
]
dynamic = [ "version" ]
dependencies = [
  "hsnf>=0.3.15",      # https://github.com/lan496/hsnf
  "numpy>=1.20.1",
  "phonopy>=2.47.1",
  "seekpath",
  "spglib>=2.7",
  "spgrep>=0.5",
  "typing-extensions",
]
optional-dependencies.dev = [
  "click",
  "ipython",
  "networkx",
  "prek",
  "pytest",
  "pytest-cov",
]
optional-dependencies.docs = [
  "docutils>=0.20",
  # "sphinx-proof",  # Seems to be incompatible with nbsphinx
  "myst-parser",
  "nbsphinx",
  "sphinx",
  "sphinx-autobuild",
  "sphinx-book-theme",
  "sphinxcontrib-bibtex",
]
optional-dependencies.vis = [
  "ase>=3.23",
  "ipykernel",
  "ipywidgets",
  "nglview>=3.0.4",
  "notebook>=7.5.6",
  "pymatgen>=2022.8.23",
]
urls.changelog = "https://phonopy.github.io/spgrep-modulation/changelog.html"
urls.documentation = "https://phonopy.github.io/spgrep-modulation"
urls.homepage = "https://phonopy.github.io/spgrep-modulation"
urls.repository = "https://github.com/lan496/spgrep-modulation"

[dependency-groups]
## #############################################################################
# Setuptools
## #############################################################################
dev = [ "spgrep-modulation[dev]" ]

[tool.setuptools]
zip-safe = false

[tool.uv]
exclude-newer = "2026-05-01"

[tool.ruff]
line-length = 99
lint.extend-select = [
  "E",  # pycodestyle-errors
  "F",  # pyflakes
  "I",  # isort
  # "D",           # pydocstyle
  "UP", # pyupgrade
]
lint.extend-ignore = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D203", # Conflict with D211
  "D205",
  "D213", # Conflict with D212
  "E501",
]

[tool.mypy]
exclude = [
  "docs",
]
warn_no_return = false

[tool.pytest]
ini_options.testpaths = [ "tests" ]
